### ISSUE TITLE
Ansible python module needs to be downgraded to deploy gridengine

### ISSUE THREAD

**Issue by tomsing1** [googlegenomics/readthedocs#127]
I set up a grid engine in a fresh virtualenv following your instructions [here](https://github.com/googlegenomics/readthedocs/blob/master/docs/source/use_cases/setup_gridengine_cluster_on_compute_engine/index.rst). 

After configuring the cluster, I tried to start it with the `elasticluster start gridengine` command, but received the following error: `ImportError: No module named callbacks`

To successfully deploy the cluster, i had to downgrade the `ansible` python module to a version < 2.0.0, e.g. by executing `pip install ansible==1.9.6` (inside the virtualenv).

**Comment by mbookman** [comment]
Could you either re-open https://github.com/gc3-uzh-ch/elasticluster/issues/236 or open a new issue against the main Elasticluster repo? They indicate that it is fixed in the development branch, and they should fix it in master.

**Comment by tomsing1** [comment]
I commented on the [reported issue](https://github.com/gc3-uzh-ch/elasticluster/issues/236) in the main elasticluster branch, as you suggested. I don't have permissions to reopen that issue, though. Let me know if you'd like me to file it as a new issue instead.
