### ISSUE TITLE
re-title BioC2015 workshop page

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/readthedocs#67]
After the conference, re-title the workshop later and add "first presented at" http://www.bioconductor.org/help/course-materials/2015/BioC2015/ with a link to the tagged version for the workshop R package in github since this material will evolve.

**Comment by pgrosu** [comment]
Good luck at the workshop!  I'm sure a lot of people will enjoy and appreciate it.

~p

**Comment by deflaux** [comment]
I did not re-title it but I did add the link to where it was presented.
